default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: <%= ENV["DATABASE_HOST"] %>

development:
  <<: *default
  database: zipper_development

test:
  <<: *default
  database: zipper_test

production:
  <<: *default
  database: zipper_production
  username: zipper
  password: <%= ENV["ZIPPER_DATABASE_PASSWORD"] %>
